# After changing this file, check it on: https://lint.travis-ci.org/
language: python
sudo: false

# Python targets, as defined by https://github.com/travis-ci/travis-build/blob
# /master/spec/build/script/python_spec.rb and https://github.com/travis-ci
# /travis-build/blob/master/lib/travis/build/script/python.rb
python:
  # Standard release https://docs.travis-ci.com/user/languages
  # /python#choosing-python-versions-to-test-against
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"  # a.k.a "nightly"

  # PyPy2.7: https://doc.pypy.org/en/latest
  # /index-of-release-notes.html#cpython-2-7-compatible-versions
  - pypy  # PyPy2.7 2.5.0
  - pypy-5.1
  - pypy-5.3
  - pypy-5.4

before_install:
  # Check default Python version installed.
  - python --version

before_script:
  - pip install codecov

script:
  # Launch unittests.
  - pip install -e .[tests]
  - pytest
  # Check coding style.
  - pycodestyle
  # Test that building packages works.
  - pip install -e .[develop]
  - ./setup.py sdist bdist_egg bdist_wheel
  # Validates package metadata.
  - ./setup.py check -m -r -s

after_script:
  - codecov

notifications:
  email:
    on_success: never
    on_failure: always
